### ISSUE TITLE
Exception using middleware

### ISSUE THREAD

**Issue by mwisner** [bitlabstudio/django-influxdb-metrics#22]
Hello,

I believe I've set everything up according to the readme, however i'm getting the following exception when using the middleware:

Python: 3.6
Django: 1.11.4
Django Metrics: 1.3.1

```
django_1         | Traceback (most recent call last):
django_1         |   File "manage.py", line 23, in <module>
django_1         |     execute_from_command_line(sys.argv)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
django_1         |     utility.execute()
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
django_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
django_1         |     self.execute(*args, **cmd_options)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
django_1         |     output = self.handle(*args, **options)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/utils.py", line 58, in inner
django_1         |     ret = func(self, *args, **kwargs)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/commands/runserver_plus.py", line 215, in handle
django_1         |     self.inner_run(options)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/commands/runserver_plus.py", line 268, in inner_run
django_1         |     handler = get_internal_wsgi_application()
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
django_1         |     return import_string(app_path)
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
django_1         |     module = import_module(module_path)
django_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
django_1         |     return _bootstrap._gcd_import(name[level:], package, level)
django_1         |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
django_1         |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
django_1         |   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
django_1         |   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
django_1         |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
django_1         |   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
django_1         |   File "/app/config/wsgi.py", line 24, in <module>
django_1         |     application = get_wsgi_application()
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
django_1         |     return WSGIHandler()
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
django_1         |     self.load_middleware()
django_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 82, in load_middleware
django_1         |     mw_instance = middleware(handler)
django_1         | TypeError: object() takes no parameters
```

Any advice? The error doesn't seem to be very obvious as to what is wrong... It comes up on every page and only when i'm using the middleware.

**Comment by sposs** [comment]
Django 1.11.4 is not compatible with python 3.6. You need at least django2.
