### ISSUE TITLE
An error when setting up development environment

### ISSUE THREAD

**Issue by a0x** [bitlabstudio/django-influxdb-metrics#23]
When I did exactly as the README says, I met this problem.
```
git config branch.autosetuprebase always
cd .git/hooks && ln -sf ../../hooks/* ./
pip install "file://`pwd`#egg=influxdb_metrics[dev]"
Processing /home/peng/workspace/django-influxdb-metrics
  django-influxdb-metrics 1.3.2 does not provide the extra 'dev'
Requirement already satisfied: python-server-metrics>=0.1.9 in ./lib/python2.7/site-packages (from influxdb_metrics[dev])
Requirement already satisfied: django>=1.6 in ./lib/python2.7/site-packages (from influxdb_metrics[dev])
Requirement already satisfied: influxdb>=2.9.1 in ./lib/python2.7/site-packages (from influxdb_metrics[dev])
Requirement already satisfied: tld in ./lib/python2.7/site-packages (from influxdb_metrics[dev])
Requirement already satisfied: psutil in ./lib/python2.7/site-packages (from python-server-metrics>=0.1.9->influxdb_metrics[dev])
Requirement already satisfied: pytz in ./lib/python2.7/site-packages (from django>=1.6->influxdb_metrics[dev])
Requirement already satisfied: python-dateutil>=2.6.0 in ./lib/python2.7/site-packages (from influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: requests>=2.17.0 in ./lib/python2.7/site-packages (from influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: six>=1.10.0 in ./lib/python2.7/site-packages (from influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./lib/python2.7/site-packages (from requests>=2.17.0->influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: idna<2.7,>=2.5 in ./lib/python2.7/site-packages (from requests>=2.17.0->influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python2.7/site-packages (from requests>=2.17.0->influxdb>=2.9.1->influxdb_metrics[dev])
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python2.7/site-packages (from requests>=2.17.0->influxdb>=2.9.1->influxdb_metrics[dev])
Installing collected packages: influxdb-metrics
Exception:
Traceback (most recent call last):
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packaes/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/peng/workspace/django-influxdb-metrics/local/lib/python2.7/site-packages/pip/wheel.py", line 347, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: influxdb_metrics[dev] .dist-info directory not found
Makefile:2: recipe for target 'develop' failed
make: *** [develop] Error 2

```
![image](https://user-images.githubusercontent.com/3829546/32336229-b8f326aa-c029-11e7-9267-4adcf7553c8e.png)

My Python is 2.7.
Pip is 9.0.1

**Comment by mbrochh** [comment]
Hmmm I''m not sure what this means. I'm not even sure why we have that line about `@egg=...[dev]` in the makefile.

I'm very busy at the moment and a quick try to `pip install -r test_requirements.txt` just failed, probably because I just updated MacOS and need to reinstall xcode and the command line tools. It's crashing to compile some C-libraries for me.

You can probably ignore the `make develop` task, I think you just need to install the test_requirememtns and then try to run `./runtests.py`

**Comment by a0x** [comment]
That's interesting. I changed the line 
```
pip install "file://`pwd`#egg=influxdb_metrics[dev]
```  
to 
```
pip install "file://`pwd`"
```
And everything works fine... until I met another problem, a trick one but not yours.
I'll deal with it, and your part is good so far.
